### ISSUE TITLE
Как это протестировать?

### ISSUE THREAD

**Issue by artginzburg** [alekseikorobov/Inputer#1]
Не очень много времени разбираться, хотелось бы просто понять, можно ли на базе этого кода сделать что-то лучше, чем Punto Switcher и Caramba Switcher? И на какой OS это должно работать, тоже не очевидно

**Comment by alekseikorobov** [comment]
Здраствуйте. Спасибо за комментарий.  Оснвано на функциях WinAPI 32. То есть работает только на Windows.
А что хотелось бы сделать лучше?
